alter table if exists public.employee_face_profiles
  add column if not exists face_embedding jsonb not null default '[]'::jsonb,
  add column if not exists face_embeddings jsonb not null default '[]'::jsonb,
  add column if not exists face_embedding_model text,
  add column if not exists face_embedding_version text,
  add column if not exists face_embedding_updated_at timestamptz;

alter table if exists public.attendance_logs
  add column if not exists face_embedding_model text,
  add column if not exists face_match_distance numeric(10, 6);

comment on column public.employee_face_profiles.face_embedding is 'Primary face descriptor vector generated by the client face embedding engine.';
comment on column public.employee_face_profiles.face_embeddings is 'Reference face descriptor samples generated during enrollment.';
comment on column public.attendance_logs.face_match_distance is 'Server-side distance between attendance descriptor and approved reference descriptor.';
