-- Biofinger ADMS user sync command queue.
-- Lets the DMS app request USERINFO from an AT-301 device through the ADMS /iclock/getrequest polling flow.

create table if not exists public.biofinger_device_commands (
  id uuid primary key default gen_random_uuid(),
  request_no bigint generated by default as identity unique,
  attendance_device_id uuid not null references public.attendance_devices(id) on delete cascade,
  serial_number text,
  command_type text not null default 'sync_users' check (command_type in ('sync_users')),
  pin text,
  command_text text,
  status text not null default 'pending' check (status in ('pending', 'sent', 'acknowledged', 'completed', 'failed', 'expired', 'cancelled')),
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 3 check (max_attempts > 0),
  response_code integer,
  response_text text,
  last_error text,
  requested_by uuid,
  requested_at timestamptz not null default now(),
  sent_at timestamptz,
  responded_at timestamptz,
  expires_at timestamptz not null default now() + interval '30 minutes',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_biofinger_device_commands_device_status
on public.biofinger_device_commands(attendance_device_id, status, requested_at desc);

create index if not exists idx_biofinger_device_commands_request_no
on public.biofinger_device_commands(request_no);

create index if not exists idx_biofinger_device_commands_expires_at
on public.biofinger_device_commands(expires_at)
where status in ('pending', 'sent');

drop trigger if exists trg_biofinger_device_commands_updated_at on public.biofinger_device_commands;
create trigger trg_biofinger_device_commands_updated_at
before update on public.biofinger_device_commands
for each row execute function public.set_updated_at();

alter table public.biofinger_device_commands enable row level security;

drop policy if exists "Production read biofinger device commands" on public.biofinger_device_commands;
create policy "Production read biofinger device commands"
on public.biofinger_device_commands for select
to authenticated
using (
  (select public.has_app_permission('biofinger.view'))
  or (select public.has_app_permission('biofinger.manage'))
  or (select public.has_app_permission('attendance.view'))
  or (select public.has_app_permission('attendance.review'))
);

drop policy if exists "Production manage biofinger device commands" on public.biofinger_device_commands;
create policy "Production manage biofinger device commands"
on public.biofinger_device_commands for all
to authenticated
using (
  (select public.has_app_permission('biofinger.manage'))
  or (select public.has_app_permission('attendance.review'))
)
with check (
  (select public.has_app_permission('biofinger.manage'))
  or (select public.has_app_permission('attendance.review'))
);

create or replace function public.request_biofinger_user_sync(
  target_device_id uuid default null,
  target_pin text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  device_row record;
  normalized_pin text := coalesce(nullif(trim(target_pin), ''), 'ALL');
  inserted_count integer := 0;
  skipped_count integer := 0;
  affected_count integer := 0;
begin
  if not (
    (select public.has_app_permission('biofinger.manage'))
    or (select public.has_app_permission('attendance.review'))
  ) then
    raise exception 'Tidak punya izin untuk meminta sync user Biofinger.';
  end if;

  for device_row in
    select id, device_code, serial_number
    from public.attendance_devices
    where (target_device_id is null or id = target_device_id)
      and status in ('active', 'maintenance')
    order by name
  loop
    insert into public.biofinger_device_commands (
      attendance_device_id,
      serial_number,
      command_type,
      pin,
      status,
      requested_by,
      metadata
    )
    select
      device_row.id,
      device_row.serial_number,
      'sync_users',
      normalized_pin,
      'pending',
      auth.uid(),
      jsonb_build_object(
        'source', 'dms-ui',
        'device_code', device_row.device_code,
        'requested_scope', case when target_device_id is null then 'all_devices' else 'single_device' end
      )
    where not exists (
      select 1
      from public.biofinger_device_commands existing_command
      where existing_command.attendance_device_id = device_row.id
        and existing_command.command_type = 'sync_users'
        and existing_command.status in ('pending', 'sent')
        and existing_command.requested_at > now() - interval '5 minutes'
    );

    get diagnostics affected_count = row_count;
    inserted_count := inserted_count + affected_count;
    if affected_count = 0 then
      skipped_count := skipped_count + 1;
    end if;
  end loop;

  if target_device_id is not null and inserted_count = 0 and skipped_count = 0 then
    raise exception 'Device Biofinger aktif tidak ditemukan.';
  end if;

  return jsonb_build_object(
    'commands_created', inserted_count,
    'commands_skipped', skipped_count,
    'pin', normalized_pin
  );
end;
$$;

revoke all on function public.request_biofinger_user_sync(uuid, text) from public;
grant execute on function public.request_biofinger_user_sync(uuid, text) to authenticated;

insert into public.audit_logs (actor_name, action, target_table, target_id, status, metadata)
values (
  'System',
  'Create Biofinger ADMS user sync command queue',
  'biofinger_device_commands',
  '20260826000100',
  'success',
  '{"source":"migration","module":"biofinger","command_queue":"user_sync"}'::jsonb
);
